version: 0.2

env:
  variables:
    REPOSITORY_URI: 998936067548.dkr.ecr.us-east-1.amazonaws.com/myecs-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Setting IMAGE_TAG...
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | cut -d':' -f2)
      - echo $IMAGE_TAG > imageTag.txt
  build:
    commands:
      - IMAGE_TAG=$(cat imageTag.txt)
      - mvn clean install
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - IMAGE_TAG=$(cat imageTag.txt)
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"spring-demo-ecr","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/*.jar
